#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../../config/environment'

state_abbr = {
  'AL' => 'Alabama',
  'AK' => 'Alaska',
  'AS' => 'America Samoa',
  'AZ' => 'Arizona',
  'AR' => 'Arkansas',
  'CA' => 'California',
  'CO' => 'Colorado',
  'CT' => 'Connecticut',
  'DE' => 'Delaware',
  'DC' => 'District of Columbia',
  'FM' => 'Micronesia1',
  'FL' => 'Florida',
  'GA' => 'Georgia',
  'GU' => 'Guam',
  'HI' => 'Hawaii',
  'ID' => 'Idaho',
  'IL' => 'Illinois',
  'IN' => 'Indiana',
  'IA' => 'Iowa',
  'KS' => 'Kansas',
  'KY' => 'Kentucky',
  'LA' => 'Louisiana',
  'ME' => 'Maine',
  'MH' => 'Islands1',
  'MD' => 'Maryland',
  'MA' => 'Massachusetts',
  'MI' => 'Michigan',
  'MN' => 'Minnesota',
  'MS' => 'Mississippi',
  'MO' => 'Missouri',
  'MT' => 'Montana',
  'NE' => 'Nebraska',
  'NV' => 'Nevada',
  'NH' => 'New Hampshire',
  'NJ' => 'New Jersey',
  'NM' => 'New Mexico',
  'NY' => 'New York',
  'NC' => 'North Carolina',
  'ND' => 'North Dakota',
  'OH' => 'Ohio',
  'OK' => 'Oklahoma',
  'OR' => 'Oregon',
  'PW' => 'Palau',
  'PA' => 'Pennsylvania',
  'PR' => 'Puerto Rico',
  'RI' => 'Rhode Island',
  'SC' => 'South Carolina',
  'SD' => 'South Dakota',
  'TN' => 'Tennessee',
  'TX' => 'Texas',
  'UT' => 'Utah',
  'VT' => 'Vermont',
  'VI' => 'Virgin Island',
  'VA' => 'Virginia',
  'WA' => 'Washington',
  'WV' => 'West Virginia',
  'WI' => 'Wisconsin',
  'WY' => 'Wyoming'
}

offset = 0
while true
  Sparql.execute(%Q{
    select ?addr ?city ?state ?state_abbr from <data> from <govtrack> WHERE {
      ?addr rdf:type o:Address;
          o:city ?city;
          o:state ?state .
        OPTIONAL {
          ?state o:shortName ?state_abbr
        }
    } limit 1000 offset #{offset}
  }, :ruby).each do |row|
    state = state_abbr[(row[:state_abbr] or row[:state])] 
    next unless state and row[:city]
    puts state + ' ' + row[:city].downcase.titleize + ' ' + offset.to_s
    Sparql.execute(%Q{
      insert into <data> { ?addr dcterms:isPartOf ?town } 
      from <data> from <census> WHERE {
        ?addr rdf:type o:Address;
	      o:city ?city;
              o:state ?state .
        OPTIONAL {
		?state o:shortName ?state_abbr
        } .
        ?town rdf:type <tag:govshare.info,2005:rdf/usgovt/Town> .
        ?town dc:title ?town_name;
        dcterms:isPartOf [  dcterms:isPartOf [ dc:title ?state_name] ]  .
        FILTER(?town_name="#{row[:city].downcase.titleize}") .
        FILTER(?state_name="#{state}") .
        FILTER(?state="#{(row[:state_abbr] or row[:state])}" || ?state_abbr="#{(row[:state_abbr] or row[:state])}") .
        FILTER(?city="#{row[:city]}")
       }
    })
  end
  break if offset > 50000
  offset += 1000
end
