#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../../config/environment'

City.all(:order => 'population DESC').each do |city|
  puts city.to_s
  city.stats # cache stats

  # store pollutants by area
  fr = Factoid.find(2).factoid_results.find(:first, :conditions => ['city_id = ? AND count3 IS NULL', city.id])
  if fr and fr.count1 and city.land_area > 0
    fr.count3 = fr.count1 / (city.land_area + city.water_area)
    puts "\t *#{fr.count3}" if fr
    fr.save
  end

#  Factoid.all.each do |factoid|
#    next if factoid.factoid_results.find(:first, :conditions => {:city_id => city.id})
#    fr = factoid.factoid_results.build(:city_id => city.id)
#    begin
#    count = factoid.count(city.location)
#    if count.compact.any?
#      count.each_with_index do |count,i|
#        fr.send("count#{i+1}=".to_sym, count) if i < 9
#      end
#      fr.save
#puts "\t* saved #{factoid.id}"
#    end
#    rescue Exception => e;
#      puts "Exception: #{e}"
#    end
#  end
end
