#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../../config/environment'

conn = Company.connection
conn.execute("select filing_id, filing_amount from lobbyists_filing where filing_amount > 0 and filing_amount is not null").each_hash do |row|
  puts row["filing_id"]
  next unless row["filing_id"]
  Sparql.execute("INSERT INTO <lobbyists> {
                 <http://www.data.gov/data/LobbyistFiling_#{row["filing_id"]}>
                 o:filingAmount
                 #{row["filing_amount"]} }")
end

