#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

City.all(:limit => 1000).each do |city|
	location = Location.new("#{city.name}, @{city.admin1_code}")
	if city.population < 1000
		print1 = FactoidDistance.create :city_id => city.id, :factoid_id => 1, :distance => 64
		FactoidDistance.create :city_id => city.id, :factoid_id => 2, :distance => 64
	else
		distance = location.find_facilities
		print1 = FactoidDistance.create :city_id => city.id, :factoid_id => 1, :distance => distance
		FactoidDistance.create :city_id => city.id, :factoid_id => 2, :distance => distance
	end
	puts print1.inspect
end